server:
  port: 2400

spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2100/eureka

    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

aliyun:
  oss:
    access-key-id: LTAI4FwHtLJ8oCxzbvypGYrW
    access-key-secret: teDY6Z96Tqid5NuxxnH1qgJkJNWW4c
    bucket-domain: http://ruxing1314.oss-cn-shanghai.aliyuncs.com
    bucket-name: ruxing1314
    end-point: http://oss-cn-shanghai.aliyuncs.com


##fastDFS配置
#fdfs:
#  #读取超时时间
#  so-timeout: 1000
#  #连接超时时间
#  connect-timeout: 600
#  #缩略图
#  thumb-image:
#    width: 60
#    height: 60
#  #tracker地址
#  tracker-list:
#    #linux上的tracker,这里填linux地址
#    -192.168.56.101:22122