server:
  port: 2600
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: leyou
    password: 123456
    virtual-host: /leyou

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2100/eureka

    #设置拉取服务的间隔时间
    registry-fetch-interval-seconds: 5
  instance:
    #过期时间
    lease-expiration-duration-in-seconds: 15
    #心跳时间
    lease-renewal-interval-in-seconds: 5
